log:
  pid: true                       # 打印PID
  console: true                   # 控制台输出
  time: true                      # 打印时间日期
  out:
    path: ./logs                  # 输出日志文件夹
    name: 'YYYY-MM-DD HH:mm:ss'   # 名称格式
    ext: 'log'                    # 后缀
    size: 100M                    # 文件按照大小分割 暂未实现